name: "PHPCodeSniffer Code Style Analyses"

on:
  # Run on all pushes and on all pull requests.
  # Prevent the build from running when there are only irrelevant changes.
  push:
    paths:
      - '**.php'
      - '.github/workflows/phpcs*'
  pull_request:
    paths:
      - '**.php'
      - '.github/workflows/phpcs*'
  # Allow manually triggering the workflow.
  workflow_dispatch:

jobs:
  phpcs:
    runs-on: [ubuntu-latest]

    name: PHPCodeSniffer

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validate composer
        run: composer validate --strict

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: PHPCodeSniffer
        run: php bin/phpcs -s --report=full --standard=.github/workflows/phpcs-ruleset.xml library
