name: "PHPCodeSniffer Code Style Analyses"

on:
  # Run on all pushes and on all pull requests.
  # Prevent the build from running when there are only irrelevant changes.
  push:
    paths:
      - '**.php'
      - '.github/workflows/phpcs*'
  pull_request:
    paths:
      - '**.php'
      - '.github/workflows/phpcs*'
  # Allow manually triggering the workflow.
  workflow_dispatch:

jobs:
  phpcs:
    runs-on: [ubuntu-latest]

    name: PHPCodeSniffer

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validate composer
        run: composer validate --strict

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --ignore-platform-req=ext-*

      - name: PHPCodeSniffer
        run: php bin/phpcs -s -p --report=full --standard=.github/workflows/phpcs-ruleset.xml library
