name: PHPUnit-9

on: [push, pull_request]

jobs:
  phpunit-php81:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Prevent entrypoint issue on load docker image jakzal/phpqa:php
        run: mv composer.json composer.json.bk
      - name: PHPUnit 9 on php 8.1
        uses: docker://jakzal/phpqa:php8.1-alpine
        with:
          args: /tools/phpunit --bootstrap tests/TestHelper.php tests/Zend/AllTests.php
  phpunit-php80:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Prevent entrypoint issue on load docker image jakzal/phpqa:php
        run: mv composer.json composer.json.bk
      - name: PHPUnit 9 on php 8.0
        uses: docker://jakzal/phpqa:php8.0-alpine
        with:
          args: /tools/phpunit --bootstrap tests/TestHelper.php tests/Zend/AllTests.php
  phpunit-php74:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Prevent entrypoint issue on load docker image jakzal/phpqa:php
        run: mv composer.json composer.json.bk
      - name: PHPUnit 9 on php 7.4
        uses: docker://jakzal/phpqa:php7.4-alpine
        with:
          args: /tools/phpunit --bootstrap tests/TestHelper.php tests/Zend/AllTests.php
          